{
 "title": "KOS Externals",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "99th Percentile Attachment Create-to-IPAM calls Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_attachment_create_to_address_latency_seconds_bucket[1m]))",
     "legendFormat": "address"
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_attachment_create_to_lock_latency_seconds_bucket[1m]))",
     "legendFormat": "IPlock"
    }
   ]
  },
  {
   "title": "95th Percentile Attachment Create-to-IPAM calls Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(kos_ipam_attachment_create_to_address_latency_seconds_bucket[1m]))",
     "legendFormat": "address"
    },
    {
     "expr": "histogram_quantile(0.95, rate(kos_ipam_attachment_create_to_lock_latency_seconds_bucket[1m]))",
     "legendFormat": "IPlock"
    }
   ]
  },
  {
   "title": "90th Percentile Attachment Create-to-IPAM calls Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(kos_ipam_attachment_create_to_address_latency_seconds_bucket[1m]))",
     "legendFormat": "address"
    },
    {
     "expr": "histogram_quantile(0.90, rate(kos_ipam_attachment_create_to_lock_latency_seconds_bucket[1m]))",
     "legendFormat": "IPlock"
    }
   ]
  },
  {
   "title": "99th Percentile Attachment Create-To-Local-Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_create_to_local_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "95th Percentile Attachment Create-To-Local-Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(kos_agent_attachment_create_to_local_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "90th Percentile Attachment Create-To-Local-Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(kos_agent_attachment_create_to_local_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "99th Percentile Attachment Create-To-Remote-Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_create_to_remote_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "95th Percentile Attachment Create-To-Remote-Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(kos_agent_attachment_create_to_remote_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "90th Percentile Attachment Create-To-Remote-Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(kos_agent_attachment_create_to_remote_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "99th Percentile Attachment Local-Ifc-to-Remote-Ifc Creation Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_impl_to_remote_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "95th Percentile Attachment Local-Ifc-to-Remote-Ifc Creation Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(kos_agent_attachment_impl_to_remote_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "90th Percentile Attachment Local-Ifc-to-Remote-Ifc Creation Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(kos_agent_attachment_impl_to_remote_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "99th Percentile Attachment Create-to-Ready Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_create_to_status_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "99th Percentile of Ping Test Duration (secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_exec_duration_secs_bucket{what=\"postCreateExec\"}[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Average Ping Test Duration (secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_attachment_exec_duration_secs_sum{what=\"postCreateExec\"}[1m])/rate(kos_agent_attachment_exec_duration_secs_count{what=\"postCreateExec\"}[1m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Ping Tests/sec, by Exit Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_attachment_exec_status_count{what=\"postCreateExec\"}[1m])",
     "legendFormat": "{{ node }} {{ exitStatus }}"
    }
   ]
  },
  {
   "title": "99th Percentile Subnet Create-to-Validated Latency secs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket{statusErr=\"ok\"}[1m]))",
     "legendFormat": "valid "
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket{statusErr=\"err\"}[1m]))",
     "legendFormat": "conflicting"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kos_subnet_validator_subnet_create_to_validated_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "total"
    }
   ]
  }
 ]
}